name: Android CI

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.5

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Access GOOGLE_FORM_ID_JA
        env:
          GOOGLE_FORM_ID_JA: ${{ secrets.GOOGLE_FORM_ID_JA }}
        run: echo GOOGLE_FORM_ID_JA=\"$GOOGLE_FORM_ID_JA\" > ./local.properties

      - name: Access GOOGLE_FORM_ID_EN
        env:
          GOOGLE_FORM_ID_EN: ${{ secrets.GOOGLE_FORM_ID_EN }}
        run: echo GOOGLE_FORM_ID_EN=\"$GOOGLE_FORM_ID_EN\" >> ./local.properties

      - name: Access GOOGLE_FORM_ID_KR
        env:
          GOOGLE_FORM_ID_KR: ${{ secrets.GOOGLE_FORM_ID_KR }}
        run: echo GOOGLE_FORM_ID_KR=\"$GOOGLE_FORM_ID_KR\" >> ./local.properties

      - name: Access GOOGLE_FORM_ID_CN
        env:
          GOOGLE_FORM_ID_CN: ${{ secrets.GOOGLE_FORM_ID_CN }}
        run: echo GOOGLE_FORM_ID_CN=\"$GOOGLE_FORM_ID_CN\" >> ./local.properties

      - name: Generate google-services.json
        env:
          GOOGLE_SERVICE_JSON: ${{ secrets.GOOGLE_SERVICE_JSON }}
        run: echo $GOOGLE_SERVICE_JSON | base64 --decode --ignore-garbage > $GITHUB_WORKSPACE/app/google-services.json

      - name: Unit Test
        run: ./gradlew testDebugUnitTest

      - name: Android Unit Test Report on Console
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}

      - name: Build with Gradle
        run: ./gradlew build

      - name: install danger
        run: |
          gem install bundler
          bundle install

      - name: run ktlint
        run: ./gradlew ktlint

      - name: run danger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gem install bundler:2.3.5
          bundle update
          bundle install
          bundle exec danger